[0m21:47:43.952202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064eb650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088689b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088686e0>]}


============================== 21:47:43.953641 | 68cc7bfc-03f2-4c7a-ad94-b280faf9862d ==============================
[0m21:47:43.953641 [info ] [MainThread]: Running with dbt=1.9.4
[0m21:47:43.953964 [debug] [MainThread]: running dbt with arguments {'log_path': 'logs', 'log_format': 'default', 'use_experimental_parser': 'False', 'write_json': 'True', 'quiet': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'version_check': 'True', 'invocation_command': 'dbt init build_mau', 'warn_error': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'empty': 'None', 'profiles_dir': '/Users/andreah/.dbt', 'cache_selected_only': 'False', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'printer_width': '80', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'fail_fast': 'False'}
[0m21:47:43.962064 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m21:47:43.965261 [info ] [MainThread]: 
Your new dbt project "build_mau" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:47:43.965428 [info ] [MainThread]: Setting up your profile.
[0m21:49:31.504161 [info ] [MainThread]: Profile build_mau written to /Users/andreah/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:49:31.512760 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 107.586205, "process_in_blocks": "0", "process_kernel_time": 0.296209, "process_mem_max_rss": "176324608", "process_out_blocks": "0", "process_user_time": 2.619244}
[0m21:49:31.514743 [debug] [MainThread]: Command `dbt init` succeeded at 21:49:31.514344 after 107.59 seconds
[0m21:49:31.515745 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e4b82f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091215b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e6ebe60>]}
[0m21:49:31.516448 [debug] [MainThread]: Flushing usage events
[0m21:49:31.873707 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:49:35.656407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104651790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10556c950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10556c6b0>]}


============================== 21:49:35.657608 | 39eeaa7f-6b7b-469a-b8fe-a73fba0fb5ec ==============================
[0m21:49:35.657608 [info ] [MainThread]: Running with dbt=1.9.4
[0m21:49:35.657910 [debug] [MainThread]: running dbt with arguments {'introspect': 'True', 'invocation_command': 'dbt debug', 'log_cache_events': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'use_colors': 'True', 'no_print': 'None', 'write_json': 'True', 'empty': 'None', 'profiles_dir': '/Users/andreah/.dbt', 'log_format': 'default', 'cache_selected_only': 'False', 'version_check': 'True', 'printer_width': '80', 'debug': 'False', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'warn_error': 'None', 'indirect_selection': 'eager', 'target_path': 'None', 'static_parser': 'True', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])'}
[0m21:49:35.665568 [info ] [MainThread]: dbt version: 1.9.4
[0m21:49:35.665767 [info ] [MainThread]: python version: 3.12.4
[0m21:49:35.665888 [info ] [MainThread]: python path: /opt/anaconda3/bin/python
[0m21:49:35.666002 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m21:49:36.062095 [info ] [MainThread]: Using profiles dir at /Users/andreah/.dbt
[0m21:49:36.062347 [info ] [MainThread]: Using profiles.yml file at /Users/andreah/.dbt/profiles.yml
[0m21:49:36.062481 [info ] [MainThread]: Using dbt_project.yml file at /Users/andreah/Documents/week10/dbt_project.yml
[0m21:49:36.062635 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m21:49:36.063440 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.43245932, "process_in_blocks": "0", "process_kernel_time": 0.351529, "process_mem_max_rss": "177209344", "process_out_blocks": "0", "process_user_time": 2.418388}
[0m21:49:36.063657 [debug] [MainThread]: Command `dbt debug` failed at 21:49:36.063618 after 0.43 seconds
[0m21:49:36.063800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10556c920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e5b7890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12f949130>]}
[0m21:49:36.063959 [debug] [MainThread]: Flushing usage events
[0m21:49:36.419482 [debug] [MainThread]: An error was encountered while trying to flush usage events
